Fixing dependencies
PeculiarVentures/webcrypto-core pull request #48
Opened 2022-03-04 21:31 UTC by miguel-a-calles-mba

The remapping causes issues when using monorepo tools such as rush.

See issue https://github.com/microsoft/rushstack/issues/3260

2022-03-04 21:32 UTC, miguel-a-calles-mba commented
The unit tests passed.

```
$ npm run test
  198 passing (41ms)
```

2022-03-06 09:35 UTC, microshine requested changes
Looks like the `@types/web` works fine

Please do changes I requested, and I'll publish this fix

2022-03-06 09:35 UTC, microshine commented on package.json
> +    "@types/web": "0.0.54",
Please change the version to `^0.0.54`
Remove `package-locg.json` file and update `yarn.lock` file. This project uses `yarn`

```
npm un @types/web
npm i yarn ---global
yarn add @types/web
```

2022-03-06 23:22 UTC, amirhmoradi commented
I get `Error: @typescript/lib-dom@npm:@types/web isn't supported by any available resolver` when using yarn 3.1+ from your latest release.
I believe this PR would fix my error too.
Thanks in advance.

2022-03-07 16:16 UTC, miguel-a-calles-mba commented
@microshine, I updated the PR. Thanks.

2022-03-07 17:34 UTC, merged

2022-03-07 17:57 UTC, microshine commented
I've published the new version `webcrypto-core@1.7.1`. Please try it

2022-03-07 19:26 UTC, miguel-a-calles-mba commented
@microshine , it's working for me in the two npm packages that lever this repo.

Any luck with your issue, @amirhmoradi?